    services:
      pocketbase:
        image: ghcr.io/muchobien/pocketbase:latest
        container_name: pocketbase
        restart: unless-stopped
        ports:
          - "8090:8090"
        volumes:
          - ./pb_data:/pb_data
        command: ["--http=0.0.0.0:8090", "--origins=http://localhost:5001,http://frontend"]
        healthcheck:
          test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
          interval: 5s
          timeout: 5s
          retries: 5
    volumes:
      pb_data:
        driver: local